import React, { useMemo } from 'react'
import PropTypes from 'prop-types'
import { Table, TableBody, TableCell, TableHead, TableRow, Paper } from '@material-ui/core'

import { HeaderTitle, CellContent, useStyles } from './helpers/styles'
import parseType from './helpers/propsParser'
import filterProps from './helpers/propsFilter'

const PropsTable = ({ propDefinitions = [] }) => {
  const classes = useStyles()
  const props = useMemo(() => filterProps(propDefinitions), [propDefinitions])

  return (
    <Paper className={classes.root}>
      <Table className={classes.table}>
        <TableHead>
          <TableRow>
            <TableCell className={classes.defaultCell}>
              <HeaderTitle>Prop</HeaderTitle>
            </TableCell>
            <TableCell className={classes.type}>
              <HeaderTitle>Type</HeaderTitle>
            </TableCell>
            <TableCell className={classes.defaultCell}>
              <HeaderTitle>Default</HeaderTitle>
            </TableCell>
            <TableCell className={classes.description}>
              <HeaderTitle>Description</HeaderTitle>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {props.map(({ defaultValue, description, property, propType, required }) => (
            <TableRow key={property}>
              <TableCell>
                <CellContent>
                  {property}
                  {required ? '*' : ''}
                </CellContent>
              </TableCell>
              <TableCell className={classes.typeCell}>
                <CellContent>{parseType(propType)}</CellContent>
              </TableCell>
              <TableCell className={classes.defaultValue}>
                <CellContent>{defaultValue}</CellContent>
              </TableCell>
              <TableCell>
                <CellContent>{description}</CellContent>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Paper>
  )
}

PropsTable.propTypes = {
  /**
   * The props definitions generated by Storybook's addon-info.
   */
  propDefinitions: PropTypes.array,
}

export default PropsTable
