import React from 'react'
import PropTypes from 'prop-types'
import Table from '@material-ui/core/Table'
import TableBody from '@material-ui/core/TableBody'
import TableCell from '@material-ui/core/TableCell'
import TableHead from '@material-ui/core/TableHead'
import TableRow from '@material-ui/core/TableRow'
import Paper from '@material-ui/core/Paper'

import { HeaderTitle, CellContent, useStyles } from './helpers/styles'
import parseType from './helpers/propsParser'

const PropsTable = ({ propDefinitions = [] }) => {
  const classes = useStyles()

  return (
    <Paper className={classes.root}>
      <Table className={classes.table}>
        <TableHead>
          <TableRow>
            <TableCell>
              <HeaderTitle>Prop</HeaderTitle>
            </TableCell>
            <TableCell className={classes.type}>
              <HeaderTitle>Type</HeaderTitle>
            </TableCell>
            <TableCell>
              <HeaderTitle>Default</HeaderTitle>
            </TableCell>
            <TableCell className={classes.description}>
              <HeaderTitle>Description</HeaderTitle>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {propDefinitions.map(({ defaultValue, description, property, propType, required }) => (
            <TableRow key={property}>
              <TableCell>
                <CellContent>
                  {property}
                  {required ? '*' : ''}
                </CellContent>
              </TableCell>
              <TableCell className={classes.typeCell}>
                <CellContent>{parseType(propType)}</CellContent>
              </TableCell>
              <TableCell className={classes.defaultValue}>
                <CellContent>{defaultValue}</CellContent>
              </TableCell>
              <TableCell>
                <CellContent>{description}</CellContent>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Paper>
  )
}

PropsTable.propTypes = {
  /**
   * The props definitions generated by Storybook's addon-info.
   */
  propDefinitions: PropTypes.array,
}

export default PropsTable
